services:
  functions:
    container_name: "${PROJECT_NAME}_functions"
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: npm run dev
    restart: always
    networks:
      my_custom_network:
        ipv4_address: ${FUNCTION_IP}

  db:
    image: mysql:latest
    container_name: "${PROJECT_NAME}_mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      my_custom_network:
        ipv4_address: ${MYSQL_IP}

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: "${PROJECT_NAME}_phpmyadmin"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_custom_network

networks:
  my_custom_network:
    external: true

volumes:
  mysql-data: